//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Project
    {
        public C_Project()
        {
            this.Apply_pro = new HashSet<Apply_pro>();
        }
    
        public int Proj_Id { get; set; }
        public string Name { get; set; }
        public string State { get; set; }
        public string Type { get; set; }
        public string Duaration { get; set; }
    
        public virtual Cnfrm_pro Cnfrm_pro { get; set; }
        public virtual ICollection<Apply_pro> Apply_pro { get; set; }
    }
}
