//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectManagementEntities : DbContext
    {
        public ProjectManagementEntities()
            : base("name=ProjectManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<C_Project> C_Project { get; set; }
        public DbSet<Cmplt_pro> Cmplt_pro { get; set; }
        public DbSet<Cnfrm_pro> Cnfrm_pro { get; set; }
        public DbSet<MemLogin> MemLogins { get; set; }
        public DbSet<SupLogin> SupLogins { get; set; }
        public DbSet<Apply_pro> Apply_pro { get; set; }
    }
}
